version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
