trailingComma: "es5"
tabWidth: 4
singleQuote: true
useTabs: true

overrides:
  - files: "*.json"
    options:
      tabWidth: 2
      useTabs: false
      singleQuote: false

  - files: "*.md"
    options:
      tabWidth: 2
      singleQuote: false

  - files: "*.yaml"
    options:
      tabWidth: 2
      useTabs: false
      singleQuote: false
