export enum StaticRoutes {
	HOME = '/',
	EVENTS = '/events',
	EVENT_DETAIL = '/events/detail',
	EVENT_CATEGORY = '/events/category',
	EVENT_TIMELINE = '/events/timeline',
	FESTIVALS = '/events/festival',
	DAYDANCES = '/events/daydance',
	COOPERATIONS = '/events/cooperation',
	IMPRESSIONS = '/events/impressions',
	BLOG = '/blog',
	BLOG_PAGE = '/blog/page',
	ARTICLE = '/blog/view',
	ABOUT_US = '/about-us',
	PORTRAIT = '/about-us/persons',
	MEMBER_PORTRAIT = '/about-us/portrait',
	PARTNERS = '/about-us/partners-and-sponsors',
	CONTACT = '/contact',
	EVENT_INQUIRY = '/contact/forms/event-booking',
	PRESS_INQUIRY = '/contact/forms/press-inquiry',
	SPONSOR_INQUIRY = '/contact/forms/sponsor',
	SUPPORT_INQUIRY = '/contact/forms/support',
	CONSULTING_INQUIRY = '/contact/forms/consulting',
	FESTIVAL_GUEST_APPEARANCE_INQUIRY = '/contact/forms/guest-appearance',
	FAQ = '/services/faq',
	LIVESTREAM = '/services/livestream',
	DATA_PROTECTION = '/services/legal/privacy',
}

export enum StaticExternalUrls {
	FACEBOOK = 'https://facebook.com/rhnklng',
	INSTAGRAM = 'https://instagram.com/rheinklang',
	SOUNDCLOUD = 'https://soundcloud.com/rhnklng',
	GITHUB = 'https://github.com/rheinklang',
	UPPTIME = 'https://status.rheinklang.events',
}
