import type { AppProps } from 'next/app';
import Head from 'next/head';
import { SWRConfig } from 'swr';
import { cmsDataFetcher, localStorageCacheProvider } from '../utils/swr';
import { Matomo } from '../components/utils/Matomo';

import '../styles/globals.css';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';

function RheinklangApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Rheinklang</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<SWRConfig value={{ provider: localStorageCacheProvider, fetcher: cmsDataFetcher }}>
				<Header />
				<Component {...pageProps} />
				<Footer />
			</SWRConfig>
			<Matomo />
		</>
	);
}

export default RheinklangApp;
