import type { AppProps } from 'next/app';
import Head from 'next/head';
import { ApolloProvider } from '@apollo/client';
import { Matomo } from '../components/utils/Matomo';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { client } from '../graphql';
import '../styles/globals.css';
import { ContentConstraint } from '../components/ContentConstraint';
import { XIcon } from '@heroicons/react/outline';
import { MarketingBanner } from '../components/MarketingBanner';

function RheinklangApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Rheinklang</title>
				<meta name="viewport" content="width=device-width, initial-scale=1 user-scalable=no" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ApolloProvider client={client}>
				<MarketingBanner text="Marketing Test Message with some pretty decent content to read" id="test" />
				<Header />
				<div>
					<Component {...pageProps} />
				</div>
				<Footer />
			</ApolloProvider>
			<Matomo />
		</>
	);
}

export default RheinklangApp;
