name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build (Node ${{ matrix.node }})

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        node: ["16"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        env:
          cache-name: next-build-cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/build/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Generate GraphQL hooks
        run: npm run graphql:generate

      - name: Build
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: true
          NEXT_PUBLIC_CMS_GRAPHQL_API_URL: ${{ secrets.CMS_GRAPHQL_API_URL }}
          NEXT_PUBLIC_CMS_REST_API_URL: ${{ secrets.CMS_REST_API_URL }}
          NEXT_PUBLIC_CMS_API_TOKEN: ${{ secrets.CMS_API_TOKEN }}
          NEXT_PUBLIC_MATOMO_URL: ${{ secrets.MATOMO_URL }}
          NEXT_PUBLIC_MATOMO_CONTAINER_ID: ${{ secrets.MATOMO_CONTAINER_ID }}
          BUILD_ID_NAMESPACE: ${{ secrets.BUILD_ID_NAMESPACE }}
          NODE_ENV: ${{ secrets.NODE_ENV }}

      - name: Deploy Website
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: website/staging/
          exclude: |
            **/.DS_Store
            **/.vscode
            **/.git*
            **/.git*/**
            **/.github/**

      - name: Deploy Styleguide
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./styleguide/
          server-dir: styleguide/corporate/
          exclude: |
            **/.DS_Store
            **/.vscode
            **/.git*
            **/.git*/**
            **/.github/**

      - name: Report issue to Slack
        if: failure() && github.ref == 'refs/heads/main'
        uses: 8398a7/action-slack@v3
        with:
          author_name: Deployment Robot
          status: ${{ job.status }}
          fields: repo,message,commit,action,eventName,ref,workflow,author,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}

  notify:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    name: Notify
    runs-on: ubuntu-latest

    steps:
      - name: Report to Slack
        uses: 8398a7/action-slack@v3
        with:
          author_name: Deployment Robot
          status: ${{ job.status }}
          fields: repo,message,commit,action,eventName,ref,workflow,author,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
