# workflow triggers
on:
  push:
    branches: [source]
  pull_request:
    branches: [source]
  workflow_dispatch:

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node ${{ matrix.node }}

    strategy:
      matrix:
        node: ["16"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm install
